name: Auto update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Update Python Script 
      run: |
        python utils/Auto update.py
    - name: Run Update Solving count.md File
      run: |
        git add .
        git diff
        git config --local user.email "piwhyjey@naver.com"
        git config --local user.name "Lab00700-Auto-Update"
        git commit -m "Automatically Update Solving count.md file"
        git push
